import type { Amenity } from './types/listing'

/** Orden estable para grids de alta/edición manual. */
export const LISTING_AMENITY_IDS: readonly Amenity[] = [
  'pool',
  'gym',
  'security_24h',
  'laundry',
  'elevator',
  'doorman',
  'storage',
  'parking',
  'balcony',
  'terrace',
  'rooftop',
  'sum',
  'garden',
  'bbq',
  'playground',
  'air_conditioning',
  'heating',
  'fireplace',
  'furnished',
  'pet_friendly',
  'wheelchair_accessible',
  'credit_approved',
  'front_facing',
]

export const LISTING_AMENITY_LABELS: Record<Amenity, string> = {
  pool: 'Pileta',
  gym: 'Gimnasio',
  security_24h: 'Seguridad 24 h',
  laundry: 'Lavadero',
  rooftop: 'Roof garden / terraza común',
  sum: 'SUM / salón de usos múltiples',
  playground: 'Juegos infantiles',
  bbq: 'Parrilla',
  garden: 'Jardín',
  balcony: 'Balcón',
  terrace: 'Terraza propia',
  parking: 'Cochera / estacionamiento',
  storage: 'Baulera',
  elevator: 'Ascensor',
  doorman: 'Portería / encargado',
  air_conditioning: 'Aire acondicionado',
  heating: 'Calefacción',
  furnished: 'Amoblado',
  pet_friendly: 'Apto mascotas',
  wheelchair_accessible: 'Accesible',
  fireplace: 'Chimenea',
  front_facing: 'Frente / contrafrente destacado',
  credit_approved: 'Apto crédito / financiación',
}
